insn_table = {
'0' : "0: Do not wear contact lenses",
'1' : "0: Take all meds with a sip of water at your usual times (except diabetes meds)",
'2' : "0: Bring the following to the hospital - inhalers, CPAP mask, eye drops",
'3' : "14: Stop taking these herbal products, nutritional supplements - ",
'3a' : "Echinacea", 
'3b' : "Ephedra", 
'3c' : "Feverfew", 
'3d' : "Garlic", 
'3e' : "Ginger", 
'3f' : "Ginkgo biloba", 
'3g' : "Ginseng", 
'3h' : "Kava Kava", 
'3i' : "Saw palmetto", 
'3j' : "St. John''s West", 
'3k' : "Fish oil", 
'3l' : "Vitamin B",
'4' : "7: Stop taking all medicines containing aspirin - ", 
'4a' : "Aspirin", 
'4b' : "Anacin", 
'4c' : "Ascriptin", 
'4d' : "Pepto-Bismol", 
'4e' : "Bufferin", 
'4f' : "Alka-Seltzer", 
'4g' : "Excedrin", 
'4h' : "Florinal", 
'4i' : "Lortab ASA",
'5': "7: Stop taking Non-Steroidal Anti-inflammatory Drugs (NSAIDs) - ",
'5a' : "Ibuprofen (Advil Motrin, Nuprin, Medipren)", 
'5b' : "Naproxen (Aleve, Anaprox, Naprosyn)", 
'5c' : "Diclofenac (Cataflam, Voltaren, Arthrotec)", 
'5d' : "Celebrex", 
'5e' : "Toradol (ketorolac)", 
'5f' : "Lodine (etodolac)", 
'5g' : "Feldene (piroxicam)", 
'5h' : "Relefeo (nuburnetce)",
'6': "7: Stop taking Accutane",
'7': "3: Stop taking Suboxone",
'8': "3: Cialis, Viagra, and Levitra",
'9': "7: Stop the following blood thinning medicines - ",
'9a' : "Plavix (Clopidogrel)", 
'9b' : "Xarelto (Rivaroxaban)", 
'9c' : "Ticlid (Ticlopidine)", 
'9d' : "Pletal (Cilostazol)", 
'9e' : "Brilinta (Ticagrelor)", 
'9f' : "Effient (prasugrel)", 
'9g' : "Aggrenox (Aspirin-Dipridarrola)",
'10': "1: Follow instructions from doctor for diabetes",
'11': "0: Do not take any medicine that is a water pill (diuretic) including - ",
'11a' : "furosemide (Lasix)", 
'11b' : "hydrochlorothiazide (HCTZ)", 
'11c' : "medicines combined with hydrochlorothiazide (HCT)",
'12' : "5: Stop blood thinner warfarin (Coumadin) - switch to Lovenox (enoxaparin) temporarily if advised by doctor",
}
default_insns = {
'0' : "0: Be prepared to spend a full day at the hospital. Wear loose, comfortable clothing and do not bring valuables. Bring a list of all medications you take.",
'1' : "0: Do not wear jewelry, wedding bands, body piercings, makeup, nail polish, or artificial nails",
'2' : "0: Do not eat or drink anything",
'3' : "1: Do not eat or drink anything after midnight (no water, coffee, gum, lifesavers, ice, food, etc.)",
'4' : "1: Do not drink any alcoholic beverages or smoke 24 hours prior to surgery",
}
